using System;
using System.Collections.Generic;
using PixlPunkt.Core.Compositing.Effects;
using PixlPunkt.Core.Effects.Settings;

namespace PixlPunkt.Core.Effects
{
    /// <summary>
    /// Registration wrapper for built-in layer effects.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This class wraps existing <see cref="LayerEffectBase"/> implementations to provide
    /// them with registration metadata and settings options for the pluggable effect system.
    /// </para>
    /// <para>
    /// Each built-in effect has a corresponding static factory method (e.g., <see cref="DropShadow"/>)
    /// that creates a fully configured registration with:
    /// </para>
    /// <list type="bullet">
    /// <item>Unique effect ID from <see cref="EffectIds"/></item>
    /// <item>Category for UI grouping</item>
    /// <item>Display name and description</item>
    /// <item>Factory for creating effect instances</item>
    /// <item>Factory for creating settings objects</item>
    /// </list>
    /// <para>
    /// <strong>Usage:</strong>
    /// </para>
    /// <code>
    /// // Register a built-in effect
    /// EffectRegistry.Shared.Register(BuiltInEffectRegistration.DropShadow());
    /// 
    /// // Or register all at once
    /// BuiltInEffects.RegisterAll();
    /// </code>
    /// </remarks>
    /// <seealso cref="IEffectRegistration"/>
    /// <seealso cref="EffectRegistry"/>
    /// <seealso cref="BuiltInEffects"/>
    public sealed class BuiltInEffectRegistration : IEffectRegistration
    {
        private readonly Func<LayerEffectBase> _factory;
        private readonly Func<LayerEffectBase, EffectSettingsBase?> _settingsFactory;

        /// <inheritdoc/>
        public string Id { get; }

        /// <inheritdoc/>
        public EffectCategory Category { get; }

        /// <inheritdoc/>
        public string DisplayName { get; }

        /// <inheritdoc/>
        public string Description { get; }

        /// <summary>
        /// Creates a new built-in effect registration.
        /// </summary>
        /// <param name="id">Unique effect ID following the convention <c>pixlpunkt.effect.{name}</c>.</param>
        /// <param name="category">Effect category for UI grouping.</param>
        /// <param name="displayName">Human-readable name shown in the UI.</param>
        /// <param name="description">Brief description of what the effect does.</param>
        /// <param name="factory">Factory function to create new effect instances.</param>
        /// <param name="settingsFactory">Factory function to create settings for an effect instance.</param>
        /// <exception cref="ArgumentNullException">Thrown if any required parameter is null.</exception>
        public BuiltInEffectRegistration(
            string id,
            EffectCategory category,
            string displayName,
            string description,
            Func<LayerEffectBase> factory,
            Func<LayerEffectBase, EffectSettingsBase?> settingsFactory)
        {
            Id = id ?? throw new ArgumentNullException(nameof(id));
            Category = category;
            DisplayName = displayName ?? throw new ArgumentNullException(nameof(displayName));
            Description = description ?? throw new ArgumentNullException(nameof(description));
            _factory = factory ?? throw new ArgumentNullException(nameof(factory));
            _settingsFactory = settingsFactory ?? throw new ArgumentNullException(nameof(settingsFactory));
        }

        /// <inheritdoc/>
        /// <remarks>
        /// The created effect instance will have its <see cref="LayerEffectBase.EffectId"/>
        /// property set to this registration's <see cref="Id"/> for registry lookup.
        /// </remarks>
        public LayerEffectBase CreateInstance()
        {
            var effect = _factory();
            effect.EffectId = Id;
            return effect;
        }

        /// <inheritdoc/>
        /// <remarks>
        /// Options are generated by creating an <see cref="EffectSettingsBase"/> instance
        /// and calling its <see cref="EffectSettingsBase.GetOptions"/> method.
        /// Returns an empty enumerable if the settings factory returns null.
        /// </remarks>
        public IEnumerable<IToolOption> GetOptions(LayerEffectBase effect)
        {
            var settings = _settingsFactory(effect);
            return settings?.GetOptions() ?? [];
        }

        //////////////////////////////////////////////////////////////////
        // STATIC FACTORY METHODS - STYLIZE EFFECTS
        //////////////////////////////////////////////////////////////////

        /// <summary>
        /// Creates registration for the drop shadow effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="DropShadowEffect"/>.</returns>
        public static BuiltInEffectRegistration DropShadow() => new(
            EffectIds.DropShadow,
            EffectCategory.Stylize,
            "Drop Shadow",
            "Adds a shadow beneath the layer with configurable offset and blur.",
            () => new DropShadowEffect(),
            effect => effect is DropShadowEffect e ? new DropShadowEffectSettings(e) : null);

        /// <summary>
        /// Creates registration for the outline effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="OutlineEffect"/>.</returns>
        public static BuiltInEffectRegistration Outline() => new(
            EffectIds.Outline,
            EffectCategory.Stylize,
            "Outline",
            "Draws a colored outline around the opaque regions of the layer.",
            () => new OutlineEffect(),
            effect => effect is OutlineEffect e ? new OutlineEffectSettings(e) : null);

        /// <summary>
        /// Creates registration for the glow/bloom effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="GlowBloomEffect"/>.</returns>
        public static BuiltInEffectRegistration GlowBloom() => new(
            EffectIds.GlowBloom,
            EffectCategory.Stylize,
            "Glow / Bloom",
            "Adds a soft glow or bloom around bright areas of the layer.",
            () => new GlowBloomEffect(),
            effect => effect is GlowBloomEffect e ? new GlowBloomEffectSettings(e) : null);

        /// <summary>
        /// Creates registration for the chromatic aberration effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="ChromaticAberrationEffect"/>.</returns>
        public static BuiltInEffectRegistration ChromaticAberration() => new(
            EffectIds.ChromaticAberration,
            EffectCategory.Stylize,
            "Chromatic Aberration",
            "Simulates lens chromatic aberration by splitting color channels.",
            () => new ChromaticAberrationEffect(),
            effect => effect is ChromaticAberrationEffect e ? new ChromaticAberrationEffectSettings(e) : null);

        //////////////////////////////////////////////////////////////////
        // STATIC FACTORY METHODS - FILTER EFFECTS
        //////////////////////////////////////////////////////////////////

        /// <summary>
        /// Creates registration for the scan lines effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="ScanLinesEffect"/>.</returns>
        public static BuiltInEffectRegistration ScanLines() => new(
            EffectIds.ScanLines,
            EffectCategory.Filter,
            "Scan Lines",
            "Adds horizontal scan lines to simulate CRT monitor appearance.",
            () => new ScanLinesEffect(),
            effect => effect is ScanLinesEffect e ? new ScanLinesEffectSettings(e) : null);

        /// <summary>
        /// Creates registration for the grain effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="GrainEffect"/>.</returns>
        public static BuiltInEffectRegistration Grain() => new(
            EffectIds.Grain,
            EffectCategory.Filter,
            "Grain",
            "Adds film grain or noise texture to the layer.",
            () => new GrainEffect(),
            effect => effect is GrainEffect e ? new GrainEffectSettings(e) : null);

        /// <summary>
        /// Creates registration for the vignette effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="VignetteEffect"/>.</returns>
        public static BuiltInEffectRegistration Vignette() => new(
            EffectIds.Vignette,
            EffectCategory.Filter,
            "Vignette",
            "Darkens the edges of the layer to draw focus to the center.",
            () => new VignetteEffect(),
            effect => effect is VignetteEffect e ? new VignetteEffectSettings(e) : null);

        /// <summary>
        /// Creates registration for the CRT effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="CrtEffect"/>.</returns>
        public static BuiltInEffectRegistration Crt() => new(
            EffectIds.Crt,
            EffectCategory.Filter,
            "CRT",
            "Simulates a cathode ray tube monitor with curvature and scan effects.",
            () => new CrtEffect(),
            effect => effect is CrtEffect e ? new CrtEffectSettings(e) : null);

        /// <summary>
        /// Creates registration for the pixelate effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="PixelateEffect"/>.</returns>
        public static BuiltInEffectRegistration Pixelate() => new(
            EffectIds.Pixelate,
            EffectCategory.Filter,
            "Pixelate",
            "Reduces resolution to create a pixelated mosaic effect.",
            () => new PixelateEffect(),
            effect => effect is PixelateEffect e ? new PixelateEffectSettings(e) : null);

        //////////////////////////////////////////////////////////////////
        // STATIC FACTORY METHODS - COLOR EFFECTS
        //////////////////////////////////////////////////////////////////

        /// <summary>
        /// Creates registration for the color adjust effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="ColorAdjustEffect"/>.</returns>
        public static BuiltInEffectRegistration ColorAdjust() => new(
            EffectIds.ColorAdjust,
            EffectCategory.Color,
            "Color Adjust",
            "Adjusts hue, saturation, and brightness in HSV color space.",
            () => new ColorAdjustEffect(),
            effect => effect is ColorAdjustEffect e ? new ColorAdjustEffectSettings(e) : null);

        /// <summary>
        /// Creates registration for the palette quantize effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="PaletteQuantizeEffect"/>.</returns>
        public static BuiltInEffectRegistration PaletteQuantize() => new(
            EffectIds.PaletteQuantize,
            EffectCategory.Color,
            "Palette Quantize",
            "Reduces colors to match a specific palette using quantization.",
            () => new PaletteQuantizeEffect(),
            effect => effect is PaletteQuantizeEffect e ? new PaletteQuantizeEffectSettings(e) : null);

        /// <summary>
        /// Creates registration for the ASCII effect.
        /// </summary>
        /// <returns>A configured <see cref="BuiltInEffectRegistration"/> for <see cref="AsciiEffect"/>.</returns>
        public static BuiltInEffectRegistration Ascii() => new(
            EffectIds.Ascii,
            EffectCategory.Color,
            "ASCII",
            "Converts the layer to ASCII art representation.",
            () => new AsciiEffect(),
            effect => effect is AsciiEffect e ? new AsciiEffectSettings(e) : null);
    }
}
